### ISSUE TITLE
don’t hard code link to jquery src

### ISSUE THREAD

**Issue by dan-nl** [europeana/Europeana-Patternlab#2]
add it to the js_files array when necessary; see [atoms/meta/_foot.mustache](https://github.com/europeana/Europeana-Patternlab/blob/db6e23ee973964aa9ac2f236231866e2f849c343/source/_patterns/atoms/meta/_foot.mustache#L5-L6)

**Comment by timharbour** [comment]
It's not a simple hard coded link. It's a link to a CDN based jquery that is widely linked to across the web and so is usually cached in a users browser cache, so speeding up page load. The js in the footer that contains the hardcoding to the local copy of jquery is a fallback for if the CDN is unavailable. 
Jquery is always required. 
T

**Comment by dan-nl** [comment]
not all projects should be forced to include jquery, nor a specific version of jquery; we want it to be an option, not a requirement. it should be possible to include the cdn link in the js_files array. as for the fallback, another variable could be included in the footer for all body js script that needs to be included; this will most likely be necessary anyway, so a variable such as js_body_script, or something similar, could be used to place the fallback to a local version of a specific version of jquery if needed.

**Comment by timharbour** [comment]
ok, I'll take a look. Just wanted you to understand that it isn't just a simple hard coded link - that script *must* be included before any other scripts that use jQuery for them to work.
It might be better to split it out into a separate template and then add variables for the specific files/urls to make sure of that.

**Comment by dan-nl** [comment]
@timharbour,

i understood what you meant, and understand that jquery needs to be included before any script tries to use it.

the idea i’m trying to convey is that the application needs to have the freedom to decide which javascript to include and make use of and should not be forced into using a specific javascript library or javascript code by the template. also, whoever is taking care of the javascript code should understand javascript dependencies and account for them.

the `{{js_files}}` variable is perfect for including any js libraries or js code files that may be needed by the application. what is missing, is a variable above those includes that the application can use to insert any js code - see the bottom of [this page’s](http://europeana1914-1918.eu) html source for an example of what i mean. a block such as the following, above the `{{js_files}}` variable would work; the variable being a string of js code supplied by the application.

```javascript
{{# js_body_script }}<script>{{ js_body_script }}</script>{{/ js_body_script }}
```

if you need to include a specific library for pattern lab, you could include it in the js_files array or if necessary in between the `{{# patternlab }}` block.

**Comment by timharbour** [comment]
yep, I get your point. I'm just a bit wary of splitting pattern lab (HTML/CSS) and the javascript so forcefully - if the application javascript isn't being used by PL it makes it far more likely that work done in PL won't reflect the reality of the application, causing bugs in the actual app that won't be picked up in development in PL. 

That JS in your {{js_body_script}} variable has to come from somewhere.

imho it's better to mix javascript and HTML in the mustache templates rather than javascript and ruby in the app isn't it?
I reckon it makes more sense to pick up any issues/conflicts between JS DOM manipulations and the existing/in development HTML + CSS in patternlab while the work's being done to build it before it ever gets to the app.

The debugging/fixing process for some JS breaking styling (or new markup breaking js functionality) would be a nightmare & a recipe for unmaintainable fixes (inline styles added by JS and !important everywhere). not great.

(re: patternlab js - there's no need for us to include any code for patternlab in {{js_files}} - it's entirely independent -  it just needs is it's own includes leaving in meta/head and meta/foot.)

**Comment by dan-nl** [comment]
as discussed, i don’t mean for dom manipulation, but for js variables, so let’s go with what we agreed on `{{# js_variables }}<script>{{ js_variables }}</script>{{/ js_variables }}` being above both the `{{jquery}}` and `{{js_files}}` includes.

developers will need to be aware that this section should not be used to inject any js that manipulates the dom and focus only on adding js variables that are needed by the application.

**Comment by andyjmaclean** [comment]
JQuery is, arguably, getting quite bloated.  Dan and I were discussing yesterday that it may be an idea to just take the parts of it we need (basically the dom selectors and the ajax utility).  The hard-coding of a JQuery library in the markup would make that impossible.

The clean approach is to not have a jquery reference in the markup - best practice would be to make each and every app explicitly declare its js dependencies.
